### ISSUE TITLE
Allow schemes other than the ones we know about

### ISSUE THREAD

**Issue by gadomski** [stac-extensions/authentication#10]
There will be schemes that aren't supported by **stac-asset**, and more generally, we can't assume to know all the different ways folks might secure their assets. It seems like some sort of fallback would be helpful, e.g. `other`. Alternatively, we could allow anything in that field, so folks could define their own keys and behavior (e.g. `my_special_authentication_scheme`).

**Comment by jamesfisher-geo** [comment]
Yup. I think allowing anything in the `type` field and having the current options as recommended standards is a great approach.
