### ISSUE TITLE
Change extension name

### ISSUE THREAD

**Issue by jamesfisher-geo** [stac-extensions/authentication#16]
With the incorporation of #15, which adds the `security:refs` parameter to Links objects, should the extension be renamed to something more descriptive before a release?

We could align the title with the field prefix -- `security`

Open to suggestions...

**Comment by gadomski** [comment]
`authentication`? Maybe with `auth` as the prefix, a la `projection` -> `proj`?

**Comment by jamesfisher-geo** [comment]
I like that!
