### ISSUE TITLE
Confusion about applicability of the extension

### ISSUE THREAD

**Issue by gadomski** [stac-extensions/authentication#17]
As I was thinking about the name change (#16), I thought about some potential implementer confusion around the applicability of this extension. Specifically, this extension (in its current form) is meant to apply only to assets, not to STAC metadata objects (Items, Collections, Catalogs) themselves. Do we need to expand the scope of this extension to apply to those metadata objects as well? A `secure-objects` extension would look almost identical to this current `secure-assets` extension.

**Comment by jamesfisher-geo** [comment]
Yeah, I think the scope should expand. The latest updates to the schema now allow an authentication scheme to be specified for Links (Items, Collections, Catalogs, etc.) like so:

```json
"security:schemes": {
    "oauth": {
      "type": "oauth2",
      "description": "requires a login and user token",
      "flows": {
        "authorizationUrl": "https://example.com/oauth/authorize",
        "tokenUrl": "https://example.com/oauth/token",
        "scopes": {}
      }
    }
  }
```
```json
"links": [
    {
      "href": "https://example.com/examples/collection.json",
      "rel": "self"
    },
    {
      "href": "https://example.com/examples/item.json",
      "rel": "item",
      "security:refs": ["oauth"]
    }
  ]
```

The README could use an update to make the two use-cases (Assets and Links) clear with examples.
