### ISSUE TITLE
How to define the parameter schema 

### ISSUE THREAD

**Issue by jamesfisher-geo** [stac-extensions/authentication#21]
PR #20 added a [parameter object](https://github.com/AtomicMaps/authentication#parameter-object), which is used to describe parameters for any authorization request using `in`, `required`, `description`, and `schema` fields. This aligns with the OpenAPI spec for [describing parameters]{https://swagger.io/docs/specification/describing-parameters/). For example, one could define the authorization request to Planetary Computer with the following:

```json
"auth:schemes": {
    "plantetary_computer_auth": {
        "type": "signedUrl",
        "description": "Requires authorization from Planetary Computer",
        "flows": {
            "authorizationCode": {
                "authorizationApi": "https://planetarycomputer.microsoft.com/api/sas/v1/sign",
                "method": "GET",
                "parameters": {
                    "href": {
                        "in": "query",
                        "required": true,
                        "description": "HREF (URL) to sign",
                        "schema": {
                            "type": "string",
                        }
                    },
                    "duration": {
                        "in": "query",
                        "required": false,
                        "description": "The duration, in minutes, that the SAS token will be valid. Only valid for approved users.",
                        "schema": {
                            "type": "integer",
                        }
                    },
                    "_id": {
                        "in": "query",
                        "required": false,
                        "description": "Third party user identifier for metrics tracking.",
                        "schema": {
                            "type": "string"
                        }
                    }
                },
                "responseField": "href"
            }
        }
    }
}
```

My issue is that the `schema` field is currently defined as an optional object in the json schema. Replicating full support for [Open API data models](https://swagger.io/docs/specification/data-models/) would be out of scope for this extension. But keeping the `schema` parameter how it is does not impose any standards on parameter schema definitions.

Perhaps a lightweight `parameterSchema` object is a good middle ground. The `parameterSchema`  object could include the following fields:
- type
- format
- example
- minimum
- maximum
- pattern

Open to comments/suggestions

**Comment by m-mohr** [comment]
Maybe just link to the JSON Schema draft-07 metaschema using a $ref?
