### ISSUE TITLE
type: planetaryComputer / earthdata

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/authentication#30]
Why do we have the type: planetaryComputer in this extension?
1. It's not used by planetaryComputer itself
2. You can describe it using signedUrl, which is actually also described with a JSON example in the README.
3. We should avoid provider specific mechanisms.

I don't see a usecase for it given that it is meant to be implemented in specs. It's unused by PC and it doesn't need to align with stac-asset as if it's not in JSON you need to define it anyway manually in stac-asset. So this extension is actually not relevant for  for this type in the stac-asset library.

I'd propose to remove it.

Same condierations should apply for earthdata, I think. If Earth Data itself doesn't expose it in JSON (does it?), why have it here?

Opinions @jamesfisher-gis ?

**Comment by jamesfisher-geo** [comment]
Agreed. I actually am not familiar with earthdata auth. 

Removed `earthdata` and `planetaryComputer` types in #32. I hope to include that in the 1.1.0 release.
