### ISSUE TITLE
S3 method and AWS signing

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/authentication#37]
@jmusial recently asked me:

> If I get it well from the [documentation](https://github.com/stac-extensions/authentication?tab=readme-ov-file#scheme-types) there is not way to in the authethification extension to check if the S3 bucket is private and requires authethification or if it is public and you should set AWS_NO_SIGN_REQUEST to no OR you sgould set --no-sign-request

My answer was:

> Thinking a bit more about it, I think if the authentication methods s3 is set, it would requires signing. So that means you'd need to remove s3 as authentication methods if it's open and aws_no_sign_request should be set. At least that sounds most reasonable to me...

Any one has thoughts on this? Maybe @jamesfisher-geo? How was this meant to work? Is my assumption correct or should we expand the s3 method with additional options?

**Comment by jamesfisher-geo** [comment]
Hi @m-mohr 

That sounds right to me. If the object is publicly available then no authentication method is needed.

**Comment by m-mohr** [comment]
Cool, thanks, I can create a PR that carifies it in the next days.

**Comment by j-musial** [comment]
@m-mohr @jamesfisher-geo I do agree that if the S3 bucket is public=freely-open (at no cost) without any S3 credentials than then the:

          "auth:refs": [
            "s3"
          ],
          
can be omitted. It has to be noted that within an Item some assets may require S3 authentication (data files) while others (quicklooks or some metadata) can have an open access.

**Comment by m-mohr** [comment]
I've added it as part of #38.
