### ISSUE TITLE
Key of the security property / De-duplication

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/authentication#4]
The spec doesn't say anything about how the key for the security property should look like or what it's useful for. If it's just an arbitrary key, would it be better to specify it as an array?

Also, a minor thing. The security property says "Object that desribes the authenticated scheme and **href**", but the href is not specified in the object. Just description and scheme.

**Comment by jamesfisher-geo** [comment]
Thanks @m-mohr. What is the advantage of specifying the security key as an array? 

Is something like this what you are suggesting?

`"security": ["SchemeKeyword", "Description of auth scheme"]`

**Comment by m-mohr** [comment]
Oh, no, I was thinking more like this:

```
"security": [
  {
    "scheme": "EarthdataClient",
    "description": "Requires a Personal Access Token"
  }
]
```

I assumed from the README (due to the Map data type) that multiple providers are possible. Looking at the examples though, it looks like the Data Type for Security is just wrong and should be just 
> [SecureAsset Object](https://github.com/AtomicMaps/secure-assets#secure-asset-object)

instead of 

> Map<string, [SecureAsset Object](https://github.com/AtomicMaps/secure-assets#secure-asset-object)>

Alternatively, I'd propose to use the array approach in case you have multiple access mechanisms.
But then I'm wondering whether this actually leads to a lot of duplication and should be somewhat centralized. 
You could define a mapping once in the Item properties and then just define the types in the assets.

Example:
```json
{
  "stac_version": "1.0.0",
  "stac_extensions": [
    "https://stac-extensions.github.io/secure-assets/v1.1.0/schema.json"
  ],
  "type": "Feature",
  "id": "item",
  "bbox": [
    172.9,
    1.3,
    173,
    1.4
  ],
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          172.9,
          1.3
        ],
        [
          173,
          1.3
        ],
        [
          173,
          1.4
        ],
        [
          172.9,
          1.4
        ],
        [
          172.9,
          1.3
        ]
      ]
    ]
  },
  "properties": {
    "datetime": "2020-12-11T22:38:32Z",
    "security:definitions": 
      "earthdata": {
        "scheme": "earthdata",
        "description": "Requires a Personal Access Token"
      },
      "none": {
        "scheme": "http",
        "description": "Free access without restrictions"
      }
  },
  "links": [
    {
      "href": "https://example.com/examples/item.json",
      "rel": "self"
    }
  ],
  "assets": {
    "data": {
      "href": "https://example.com/examples/file.xyz",
      "title": "Secure Asset Example",
      "type": "application/vnd.example",
      "roles": [
        "data"
      ],
      "security:refs": ["earthdata"]
    },
    "thumbnail": {
      "href": "https://example.com/examples/thumb.png",
      "title": "Thumbnail",
      "type": "image/png",
      "roles": [
        "thumbnail"
      ],
      "security:refs": ["earthdata", "none"]
    }
  }
}
```

I think I'd prefer this approach as it leads to less duplication (imaging 20 bands in individual files, i.e. 20x the security definitions.
Also, for example thumbnails could be accessed with and without auth, while the data is only with auth.

**Comment by gadomski** [comment]
@m-mohr how would the `refs` idea work w/ the `alternate_assets` extension, e.g. in the [USGS Landsat's STAC catalog](https://landsatlook.usgs.gov/stac-server/collections/landsat-c2l2-sr/items/LC09_L2SR_082075_20230804_20230806_02_T1_SR)? Is it as simple as this?

```json
{
  "stac_version": "1.0.0",
  "stac_extensions": [
    "https://stac-extensions.github.io/secure-assets/v1.1.0/schema.json"
  ],
  "type": "Feature",
  "id": "item",
  "bbox": [
    172.9,
    1.3,
    173,
    1.4
  ],
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          172.9,
          1.3
        ],
        [
          173,
          1.3
        ],
        [
          173,
          1.4
        ],
        [
          172.9,
          1.4
        ],
        [
          172.9,
          1.3
        ]
      ]
    ]
  },
  "properties": {
    "datetime": "2020-12-11T22:38:32Z",
    "security:definitions": 
      "requester_pays": {
        "scheme": "requester_pays",
        "description": "Uses AWS's requester pays mechanism to pay for data egress"
      },
      "none": {
        "scheme": "http",
        "description": "Free access without restrictions"
      },
      "usgs_eros": {
        "scheme": "usgs_eros",
        "description": "Requires a M2M token for the USGS EROS servers, which requires manual approval via a web form. Currently unsupported by stac-asset"
      }
  },
  "links": [
    {
      "href": "https://example.com/examples/item.json",
      "rel": "self"
    }
  ],
  "assets": {
    "data": {
      "href": "https://example.com/examples/file.xyz",
      "title": "Secure Asset Example",
      "type": "application/vnd.example",
      "roles": [
        "data"
      ],
      "security:refs": ["usgs_eros"],
      "alternate": {
        "s3": {
          "storage:platform": "AWS",
          "storage:requester_pays": true,
          "href": "s3://example/examples/file.xyz",
          "security:refs": ["requester_pays"],
        }
      }
    },
    "thumbnail": {
      "href": "https://example.com/examples/thumb.png",
      "title": "Thumbnail",
      "type": "image/png",
      "roles": [
        "thumbnail"
      ],
      "security:refs": ["none"]
    }
  }
}
```

**Comment by m-mohr** [comment]
Looks good :-)

**Comment by gadomski** [comment]
@m-mohr per your comment https://github.com/AtomicMaps/secure-assets/issues/7#issuecomment-1667557086, should my example pull the `storage:*` keys into `security:defintions` as well? E.g. (snipped):

```json
{
  "properties": {
    "security:definitions": 
      "requester_pays": {
        "scheme": "requester_pays",
        "description": "Uses AWS's requester pays mechanism to pay for data egress",
        "storage:platform": "AWS",
        "storage:requester_pays": true,
      },
  },
  "assets": {
    "data": {
      "href": "https://example.com/examples/file.xyz",
      "title": "Secure Asset Example",
      "type": "application/vnd.example",
      "roles": [
        "data"
      ],
      "security:refs": ["usgs_eros"],
      "alternate": {
        "s3": {
          "href": "s3://example/examples/file.xyz",
          "security:refs": ["requester_pays"],
        }
      }
    }
  }
}
```

**Comment by m-mohr** [comment]
That's a good question. I don't think it should be, security seems more specific than storage. If at all, it might be the other way around (security in storage). But maybe it should just be separate?

**Comment by jamesfisher-geo** [comment]
Agreed. I think defining `security:definitions` in the item properties and `security:refs` in the asset is a great approach. 

Defining storage parameters in the security definition seems redundant. But I suppose that there are use cases for having the provider explicitly defined. Perhaps the extensions can be merged once secure-assets is more mature. 

Does the community lean more toward merging extensions, or keeping specific extensions separate?

**Comment by m-mohr** [comment]
I'm not aware of any extensions that have been merged so far.

**Comment by jamesfisher-geo** [comment]
I have addressed this issue in the latest round of edits. Like @m-mohr's example above, I added a field for scheme definitions. The field is named "security:schemes" to align with the OpenAPI spec, per discussion in issue #8
