### ISSUE TITLE
Suggestion: remove top-level iterable

### ISSUE THREAD

**Issue by gadomski** [stac-extensions/authentication#5]
I believe the ability to use more than one access pattern for a single asset is already provided by the [alternate assets extension](https://github.com/stac-extensions/alternate-assets). I'd suggest leveraging that extension and only define `secure_assets:scheme` (and others) as attributes on assets or alternate asset objects.

**Comment by m-mohr** [comment]
I'm not sure about it.
What about a HTTP thumbnail that can be accessed with and without authentication as in the example in https://github.com/AtomicMaps/secure-assets/issues/4#issuecomment-1667543042 ? We use that mechanism in openEO instances...

**Comment by gadomski** [comment]
> What about a HTTP thumbnail that can be accessed with and without authentication as in the example in https://github.com/AtomicMaps/secure-assets/issues/4#issuecomment-1667543042 ?

Good point. Closing.
