### ISSUE TITLE
Suggestion: choose different noun than `scheme`

### ISSUE THREAD

**Issue by gadomski** [stac-extensions/authentication#6]
While access patterns _usually_ map to URI scheme, they don't always. For example, the [Earthdata client](https://github.com/stac-utils/stac-asset#earthdata) reads `http(s)` URIs, but requires extra configuration in the form of an access token. I'm not sure of the right noun yet, maybe `client`?

**Comment by m-mohr** [comment]
Seems related to https://github.com/AtomicMaps/secure-assets/issues/3
Maybe remove "client" from the values and use it as a kay?

On the other hand, OpenAPI also calls it security scheme: https://swagger.io/docs/specification/authentication/

**Comment by gadomski** [comment]
> On the other hand, OpenAPI also calls it security scheme: https://swagger.io/docs/specification/authentication/

That's a good argument for keeping `scheme`, I think. Closing.
