### ISSUE TITLE
Align (or combine) with storage extension

### ISSUE THREAD

**Issue by gadomski** [stac-extensions/authentication#7]
The [storage extension](https://github.com/stac-extensions/storage) exists in a similar problem space to this repo. Does this extension provide enough extra value to stand on its own (especially if #5 is adopted)? Or could its concepts be rolled into `storage`?

If this extension should live on its own, `storage:platform` and `secure_assets:scheme` will be very similar, and could leverage each other in some way.

**Comment by m-mohr** [comment]
Related to my comment in https://github.com/AtomicMaps/secure-assets/issues/4#issuecomment-1667543042, I think. I think this extension should be allowed to be used in the storage extension, maybe also alternate assets and assets. But then only refer back to a "central map" of auth mechanisms to avoid duplication.

**Comment by jamesfisher-geo** [comment]
Thanks @gadomski. I think that, with the latest updates based on #4 and #8, the extension can stand on it's own. The latest version can work alongside the `storage` extension like how you described in #4   : )
